### ISSUE TITLE
Build instructions in README seem obsolete

### ISSUE THREAD

**Issue by snej** [openziti/tlsuv#169]
I just cloned the repo and am trying to build the main branch. The instructions in the README don’t seem to describe the current state of the repo:

* "Dependencies (libuv, and mbedTLS) are specified as git submodules” — Nope, there are no submodules in the repo.
* "We use [Cmake](https://cmake.org/) as our build system. Any of the standard generators(makefile, [ninja](https://ninja-build.org/)) should be working fine, let us know if you see any issues.” — I did the usual `mkdir build && cd build && cmake ..` incantation on my macOS system and got the following error:

```
CMake Error at CMakeLists.txt:75 (find_package):
  Could not find a package configuration file provided by "llhttp" with any
  of the following names:

    llhttpConfig.cmake
    llhttp-config.cmake

  Add the installation prefix of "llhttp" to CMAKE_PREFIX_PATH or set
  "llhttp_DIR" to a directory containing one of the above files.  If "llhttp"
  provides a separate development package or SDK, be sure it has been
  installed.
```

There’s no mention of `llhttp` in the README. I can try installing it with homebrew and see if that resolves the issue.

**Comment by dovholuknf** [comment]
Yeah, lots of changes that aren't relevant anymore for sure! thanks for filing an issue.

**Comment by snej** [comment]
I found the [llhttp repo](https://github.com/nodejs/llhttp) but I’m confused — it’s primarily TypeScript. There are instructions in its README for using it in C code with CMake, but it has instructions for what to put in your CMakeLists and it looks nothing like what the diagnostics above say to do.

Sort of frustrating because I don’t really need an HTTP parser; all I want is TLS support for libuv.

**Comment by ekoby** [comment]
> I found the [llhttp repo](https://github.com/nodejs/llhttp) but I’m confused — it’s primarily TypeScript. There are instructions in its README for using it in C code with CMake, but it has instructions for what to put in your CMakeLists and it looks nothing like what the diagnostics above say to do.
> 
> Sort of frustrating because I don’t really need an HTTP parser; all I want is TLS support for libuv.

I believe llhttp C implementation is generated from Typescript. 

After seeing your use case I am considering making HTTP support optional. This will reduce the number of dependencies (llhttp, zlib) for that usage

**Comment by plajjan** [comment]
I too only want TLS for libuv (using mbedtls in my case). I'm using the zig build system, so wrote my own build config for that but I'd a) like to upstream that if it's interesting to the project and b) think llhttp should be made optional, regardless if the build system is zig, cmake or something else :)
